version: "3.8"

services:
  php:
    build: ./build/php/
    image: php-fpm:latest
    #container_name: php-fpm
    restart: unless-stopped
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - php:/php
      - app:/app

  nginx:
    build: ./build/nginx
    image: nginx:latest
    #container_name: nginx
    restart: unless-stopped
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - php:/php
      - app:/app
    ports:
      - "8080:8080"

#  db:
#    image: postgres:alpine
#    container_name: postgres
#    restart: unless-stopped
#    networks:
#      - php-app
#    volumes:
#      - app_db:/var/lib/postgresql/data
#    environment:
#      - POSTGRES_USER=db_user
#      - POSTGRES_PASSWORD=db_password
#      - POSTGRES_DB=database

  db:
    image: mariadb:latest
    container_name: db
    restart: unless-stopped
    volumes:
      - app_db:/var/lib/postgresql/data
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_DATABASE=database
      - MYSQL_USER=db_user
      - MYSQL_PASSWORD=db_password

volumes:
  php:
  app:
  app_db:
